"""Every page this repository publishes is a COMPLETE document, not a fragment.

WHY THIS FILE EXISTS
--------------------
`docs/verification.html` shipped as a bare body: `build_verification()` returned its sections
without ever calling `page()`, so the published file had no doctype, no navigation and no footer -
a dead end on a site whose whole point is that a reader can walk from any claim to its evidence.
Nothing failed, because the only navigation test asserted that `page()` puts a link in the nav it
builds; nothing asserted that each *builder* used it.

These tests are deliberately about the generated FILES rather than the builder functions: they are
the bytes that get published, and they are what a reader (or a crawler) actually receives.
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
sys.path.insert(0, str(ROOT))

REQUIRED_NAV = ("index.html", "executive_summary.html", "how_to_submit.html", "submission.html",
                "data.html", "metric.html", "method.html", "results.html", "sources.html",
                "verification.html", "review.html", "reproduce.html")


def _generated_pages() -> list[Path]:
    mod = _site_mod()
    return sorted(mod.DOCS.glob("*.html"))


def _site_mod():
    import importlib.util
    spec = importlib.util.spec_from_file_location("build_site", ROOT / "scripts" / "build_site.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


@pytest.mark.skipif(not any(DOCS.glob("*.html")), reason="the site has not been generated here")
def test_every_published_page_is_a_complete_document():
    for p in _generated_pages():
        text = p.read_text(encoding="utf-8")
        assert text.lstrip().startswith("<!DOCTYPE html>"), f"{p.name} is not a full document"
        assert text.rstrip().endswith("</html>"), f"{p.name} is truncated"
        assert "<title>" in text and "</title>" in text, f"{p.name} has no title"


@pytest.mark.skipif(not any(DOCS.glob("*.html")), reason="the site has not been generated here")
def test_every_page_carries_the_whole_nav():
    for p in _generated_pages():
        text = p.read_text(encoding="utf-8")
        missing = [h for h in REQUIRED_NAV if f'href="{h}"' not in text]
        assert not missing, f"{p.name} cannot reach {missing}"
        # exactly one entry may be marked active, and it must be this page
        actives = re.findall(r'<a href="([a-z_]+\.html)" class="active">', text)
        assert actives == [p.name], f"{p.name}: active nav entries {actives}"


@pytest.mark.skipif(not any(DOCS.glob("*.html")), reason="the site has not been generated here")
def test_no_page_links_to_a_page_that_does_not_exist():
    published = {p.name for p in _generated_pages()}
    for p in _generated_pages():
        for target in re.findall(r'href="([a-z_]+\.html)', p.read_text(encoding="utf-8")):
            assert target in published, f"{p.name} links to {target}, which is not published"


STAMP = re.compile(rb"\d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC")


def _normalised(p: Path) -> bytes:
    """Page bytes with the build stamp neutralised.

    Every page ends with `Generated by scripts/build_site.py … · <now> UTC`, so two builds of the
    same evidence are byte-identical only inside the same clock minute.  Comparing raw bytes would
    therefore make this test fail on a minute boundary - a flake, not a defect.  The stamp is the
    one thing on the page that is *supposed* to change, and everything else is not.
    """
    return STAMP.sub(b"<STAMP>", p.read_bytes())


# The build reads the working tree as well as the committed evidence: `docs/submission.html`
# reports whether the three official rasters are present RIGHT NOW, and `data/*.tif` is gitignored
# by design (418 MB + 0.4 MB + 1.6 MB).  So the committed page can only match a build in a checkout
# that has the rasters, while CI - a fresh clone - legitimately renders "ABSENT" instead.  These
# markers name every string that may differ for that reason and nothing else; anything outside them
# is drift, which is what this test exists to catch.  (Discovered by this test failing on the
# runner, which is the correct behaviour: the alternative was a silently stale page.)
LIVE_STATE_MARKERS = (b"MATCHES THE PIN", b"pill bad", b"data/ is not populated in this checkout",
                      b"<strong>Ready.</strong> All three canonical rasters")


def _strip_live_state(html: bytes) -> bytes:
    """Drop the lines that report the working tree's own state, keep everything else."""
    kept = [ln for ln in html.splitlines(keepends=True)
            if not any(m in ln for m in LIVE_STATE_MARKERS)]
    return b"".join(kept)


def _comparable(p: Path) -> bytes:
    return _strip_live_state(_normalised(p))


def test_the_build_reproduces_the_committed_pages(tmp_path):
    """The site IS a build artifact: regeneration must be a no-op.

    Without this, a page can be edited by hand (or go stale against the evidence it renders) and
    nothing notices - which is the failure mode the whole repository is built to avoid.  The one
    exception is documented above and is exactly as wide as the live-state markers.
    """
    if not any(DOCS.glob("*.html")):
        pytest.skip("the site has not been generated here")
    # Build into a copy. Building in place used to leave `git status` dirty (the build stamp moves),
    # and worse: comparing a page to a rebuild of itself in the same tree can only see what the
    # rebuild overwrote, so a hand-edited page was "reproduced" by editing it back.
    committed = {p.name: _comparable(p) for p in _generated_pages()}
    fresh = tmp_path / "docs"
    subprocess.run([sys.executable, str(ROOT / "scripts" / "build_site.py"), "--out-dir", str(fresh)],
                   cwd=ROOT, check=True, capture_output=True)
    built = {p.name: _comparable(p) for p in sorted(fresh.glob("*.html"))}
    assert built, "the fresh build produced no pages at all"
    changed = sorted(n for n in committed if n in built and committed[n] != built[n])
    assert not changed, f"the committed pages are stale against a rebuild: {changed}"
    extra = sorted(set(built) - set(committed))
    assert not extra, f"the builder emits pages that are not committed: {extra}"


def test_building_twice_in_one_environment_is_byte_identical(tmp_path):
    """Determinism, independent of the live-state exception: two builds here must agree exactly."""
    if not any(DOCS.glob("*.html")):
        pytest.skip("the site has not been generated here")
    snapshots = []
    for i in range(2):
        target = tmp_path / f"docs{i}"
        subprocess.run([sys.executable, str(ROOT / "scripts" / "build_site.py"),
                        "--out-dir", str(target)], cwd=ROOT, check=True, capture_output=True)
        snapshots.append({p.name: _normalised(p) for p in sorted(target.glob("*.html"))})
    first, second = snapshots
    assert first, "no pages were built"
    changed = sorted(n for n in first if first[n] != second[n])
    assert not changed, f"two consecutive builds differ in {changed}"


def test_every_page_carries_a_build_stamp():
    """The stamp is the one volatile byte on a page, so it must at least be present and well-formed."""
    for p in _generated_pages():
        stamps = STAMP.findall(p.read_bytes())
        assert len(stamps) == 1, f"{p.name} has {len(stamps)} build stamps"
