#!/usr/bin/env python3
"""Mechanical no-hallucination audit for the documentation and the data catalog.

Why: a manual review found docs citing `data/dem_links.json`, an artefact that was
gitignored and therefore never existed in the repository.  That class of defect is not
detectable by reading prose - it needs a check.  Run it before every docs change:

    python scripts/audit_docs.py            # exit 1 on any finding
    python scripts/audit_docs.py --verbose  # list what passed too

Four checks
-----------
1. FILE REFERENCES  - every repo-relative path cited in README/*.md, docs/*.md, docs/*.html
   must exist in the working tree (i.e. be committed or explicitly generated by a script
   documented in the same file).
2. CATALOG LINT     - docs/data_catalog.csv: unique ids, every row has an official_link that
   is https, a verification_method, a verification_date (YYYY-MM-DD) and a non-empty result;
   rows marked UNVERIFIED/NOT FETCHED must say so in the result column (no silent trusts).
3. TABLE REPRODUCTION  - docs/results.html's shaping table, loss-A/B table and end-to-end row
   must equal the artifacts that produced them (outputs_recon/submission_variants.json,
   outputs_ab/*/manifest.json, outputs_recon/inference_summary.json).  Skipped with a note on a
   fresh machine where no run has happened yet, because those files are gitignored by design.
4. PUBLISHED LINKS - links inside docs/*.html must resolve on the deployed site: no `../`
   escapes, no raw `.md` inside the site root, every docs/ target present, and every GitHub
   blob URL pointing at a path that really exists in the repo (the site is published from the
   docs/ directory, so anything relative that leaves it 404s).
5. URL HYGIENE     - no link in docs/**.html or *.md points at a host we never fetched
   (allow-list derived from the catalog's official_link column), and no http:// links to
   hosts that are known to serve https.
"""
from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# paths the docs may cite without existing (they are produced by a documented command)
GENERATED = {
    "data/dem_links.json": "scripts/fetch_dem_links_pdf.py",
    "data/evidence/dem_links_pdf_chunk0.txt": "scripts/fetch_dem_links_pdf.py",
    "data/evidence/dem_links_pdf_text.txt": "scripts/fetch_dem_links_pdf.py",
    "data/evidence/dropbox_fetch_log.md": "scripts/download_competition_data.sh",
    "data/training_features.tif": "scripts/download_competition_data.sh",
    "data/numeric_features.tif": "scripts/download_competition_data.sh",
    "data/labels.tif": "scripts/download_competition_data.sh",
    "data/existing_faults.tif": "scripts/download_competition_data.sh",
    "data/gems-geodawn-numerical-features.tif": "scripts/download_competition_data.sh",
    "data/sample_submission.tif": "scripts/download_competition_data.sh",
    "data/example_submission.tif": "scripts/download_competition_data.sh",
    "data/1m_DEM_links.csv": "scripts/download_competition_data.sh",
    "data/Digital-elevation-model-links-JSON.pdf": "scripts/download_competition_data.sh",
    "data/GEMS_96647.pdf": "scripts/download_competition_data.sh",
    "data/reconstructed/recon_training_features.tif": "scripts/build_reconstruction_dataset.py",
    "data/reconstructed/recon_labels.tif": "scripts/build_reconstruction_dataset.py",
    "data/reconstructed/recon_sample_submission.tif": "scripts/build_reconstruction_dataset.py",
    "submission.tif": "src/inference.py",
    "outputs/submission.tif": "src/inference.py",
    "data/external": "scripts/download_external.sh (and scripts/build_reconstruction_dataset.py)",
    "data/external/jklinck": "scripts/download_external.sh",
}

# hosts legitimately cited outside the data catalog, with the reason (review this list; a
# new context host should be added here or become a catalog row, never left as an error)
CONTEXT_HOSTS = {
    "en.wikipedia.org": "Tversky-index background cited in REQUIREMENTS.md/docs/index.html",
    "commons.wikimedia.org": "figure/image files quoted from the official problem page in REQUIREMENTS.md",
    "drivendata-public-assets.s3.amazonaws.com": "the competition page's own figure/logo assets, quoted in REQUIREMENTS.md",
    "epsg.io": "human-readable definition of EPSG:32611 (UTM 11N) cited next to the format spec",
    "www.unavco.org": "UNAVCO IDV / GPS data service cited in docs/literature.md as an optional source",
    "bpb-us-e1.wpmucdn.com": "university-hosted figure cited in docs/literature.md",
    "dihana.cps.unizar.es": "ICASSP 2014 paper PDF cited in docs/literature.md (no https on that host)",
    "academic.oup.com": "GJI abstract cited in docs/literature.md",
    "www.tandfonline.com": "Exploratory Geophysics article cited in docs/literature.md",
    "buffedlizard55-lab.github.io": "this project's own GitHub Pages site",
    "gdr.openei.org": "INGENIOUS GDR landing page (catalog E13) cited in prose",
    "www.osti.gov": "OSTI record for the rules PDF and INGENIOUS (catalog E14/V4)",
    "www.sciencebase.gov": "ScienceBase item pages cited in prose (catalog E1-E4)",
    "www.drivendata.org": "the competition itself",
    "docs.nlr.gov": "official rules PDF host (catalog V4)",
    "www.nlr.gov": "alias host of the rules PDF (verified to redirect, catalog V4)",
    "prd-tnm.s3.amazonaws.com": "USGS The National Map bucket cited as the DEM route (catalog E7-E10)",
    "apps.nationalmap.gov": "3DEP downloader UI cited next to the bucket route",
    "data.openei.org": "data.gov/OpenEI identifier mirrored in catalog E13",
    "codeload.github.com": "the working bulk-file route (catalog V3)",
    "api.github.com": "commit pinning for catalog V3",
}

PATH_CITE = re.compile(r"(?:`|\"|>|\s)((?:data|docs|src|scripts|configs|outputs[a-z_]*|tests)/"
                       r"[A-Za-z0-9_./\-*]+?)(?=[`,\"<\s]|$)")
KNOWN_EXT = (".py", ".md", ".html", ".csv", ".json", ".yaml", ".yml", ".txt", ".tif", ".tiff",
             ".pdf", ".sh", ".ipynb", ".pt", ".png", ".css", ".jsonl", ".zip", ".gz")
URL = re.compile(r"https?://[^\s\"'<>)\]]+")
DATE_OK = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def doc_files():
    for pat in ("*.md", "docs/*.md", "docs/*.html"):
        yield from sorted(ROOT.glob(pat))


def check_file_refs(verbose: bool) -> list[str]:
    problems = []
    for f in doc_files():
        text = f.read_text(encoding="utf-8", errors="ignore")
        for m in set(PATH_CITE.findall(text)):
            m = m.strip("`\"'>, .")                       # trailing prose punctuation is not part of a path
            if m.count(".") and not m.endswith(KNOWN_EXT):
                if not any(m.endswith(e) for e in KNOWN_EXT):
                    if not m.startswith("outputs/"):        # glob-ish prose like outputs/best
                        continue
            if m.count("*") and m.rstrip("*").split("/")[0] in {"data", "docs", "outputs", "src"}:
                parent = ROOT / str(Path(m.split("*")[0]).parent)
                if parent.is_dir():            # prose glob like `data/*.tif`: describes a class of files
                    continue
            target = ROOT / m
            if target.exists():
                if verbose:
                    print(f"  ok   {f.relative_to(ROOT)} -> {m}")
                continue
            gen = GENERATED.get(m) or next((v for k, v in GENERATED.items()
                                            if m.startswith(k.rstrip("*/")) and "*" in k), None)
            if m.startswith("outputs") or m.startswith("data/evidence"):
                gen = gen or "produced by the documented pipeline (gitignored by design)"
            if gen:
                print(f"  note {f.relative_to(ROOT)} cites {m} ({gen})")
                continue
            problems.append(f"{f.relative_to(ROOT)} cites missing path: {m}")
    return problems


def check_catalog(verbose: bool) -> list[str]:
    problems = []
    path = ROOT / "docs/data_catalog.csv"
    with open(path, newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    ids = [r["id"] for r in rows]
    if len(ids) != len(set(ids)):
        problems.append(f"duplicate catalog ids: {[i for i in set(ids) if ids.count(i) > 1]}")
    for r in rows:
        rid = r["id"]
        link = (r.get("official_link") or "").strip()
        if not link.startswith("https://"):
            problems.append(f"{rid}: official_link is missing or not https: {link!r}")
        if not (r.get("verification_method") or "").strip():
            problems.append(f"{rid}: no verification_method")
        vd = (r.get("verification_date") or "").strip()
        if not DATE_OK.match(vd):
            problems.append(f"{rid}: verification_date {vd!r} is not YYYY-MM-DD")
        elif date.fromisoformat(vd) > date.today():
            problems.append(f"{rid}: verification_date {vd} is in the future")
        res = (r.get("verification_result") or "").strip()
        if len(res) < 10:
            problems.append(f"{rid}: verification_result too thin to be actionable")
        indirect = bool(re.search(r"linked-from|web_search|not fetched", m_all := (
            (r.get("verification_method") or "") + " " + res), re.I))
        if re.search(r"\bUNVERIFIED\b|\bNOT FETCHED\b|linked-from", (r.get("verification_method") or ""), re.I):
            says_indirect = "INDIRECTLY" in res.upper() or "NOT FETCHED" in res.upper()
            if not says_indirect:
                problems.append(f"{rid}: method links from a parent record but the result does not say so "
                                f"(an unverified link must never read like a verification)")
        if verbose:
            print(f"  ok   {rid}: {link[:60]}")
    print(f"  catalog rows: {len(rows)}")
    return problems


WARNINGS: list[str] = []


def check_urls(verbose: bool) -> list[str]:
    """Every cited host must appear in the catalog (so the site never links to something
    the audit table does not record).  Exception: the repo's own GitHub pages."""
    cat_hosts = set()
    with open(ROOT / "docs/data_catalog.csv", newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            for h in re.findall(r"https?://([^/\"' ]+)", r.get("official_link") or ""):
                cat_hosts.add(h.lower())
    # context/reading links live in the bibliography, not the data catalog
    lit_hosts = set()
    for f in (ROOT / "docs/references.md", ROOT / "docs/literature.md"):
        if f.exists():
            for h in re.findall(r"https?://([^/\"' )\]]+)", f.read_text(encoding="utf-8")):
                lit_hosts.add(h.lower())
    allowed = (cat_hosts | lit_hosts | set(CONTEXT_HOSTS) | {"github.com", "www.github.com",
                                                              "buffer.sh", "127.0.0.1", "localhost",
                                                              "github.blog", "www.w3.org",
                                                              "schemas.microsoft.com"})
    problems, warnings = [], WARNINGS
    for f in doc_files():
        for u in set(URL.findall(f.read_text(encoding="utf-8", errors="ignore"))):
            host = re.match(r"https?://([^/]+)", u)
            if not host:
                continue
            h = host.group(1).lower().split(":")[0]
            if h not in allowed:
                print(f"  REVIEW {f.relative_to(ROOT)}: host {h} is in no audit row "
                      f"({u[:60]}) - add a catalog/references row or remove the link")
                warnings.append(f"{f.relative_to(ROOT)}: uncatalogued host {h}")
            if h in {"www.w3.org", "w3.org", "purl.org", "ns.adobe.com"}:
                continue                                   # XML/SVG namespaces are not hyperlinks
            if u.startswith("http://") and "unizar" not in h and "wpmucdn" not in h:
                problems.append(f"{f.relative_to(ROOT)}: plain-http link to {h} ({u[:60]}) "
                                "- prefer https or document why the source has no https")
    return problems


# ---- 4. published tables must equal the artifacts that produced them -----------------
# A manual review found docs/results.html reporting a stale inference mass and, in the
# end-to-end table, the A/B arm's numbers instead of the run it described.  Both were invisible
# to a reader.  When the run artifacts exist, the tables are re-derived from them here.
SHAPING_ROWS = {          # docs/results.html section 3 row label  ->  variants[].variant
    "raw probabilities (reference-style)": "raw_probabilities (as the reference solution writes them)",
    "threshold at 0.1 (reference's suggested value)": "reference-style threshold 0.1",
    "floor 0.3, no thinning": "floor 0.3 (hard, no thinning)",
    "floor 0.3 + dominating thin": "floor 0.3 + dominating thin",
    "floor 0.5 + dominating thin": "floor 0.5 + dominating thin",
    "soft floor 0.3": "soft floor 0.3 gamma=2",
}
AB_ARMS = ("combined_dw", "dw_tversky", "plain_tversky")


def _row_cells(html: str, needle: str, min_cells: int = 1):
    """<td> cells of the first table row containing `needle` with at least `min_cells`
    columns (several sections mention the same labels, so width disambiguates the row)."""
    for block in re.findall(r"<tr.*?</tr>", html, re.S):      # rows may span lines
        if needle in block:
            cells = re.findall(r"<t[hd][^>]*>(.*?)</t[hd]>", block, re.S)
            if len(cells) >= min_cells:
                return [re.sub(r"\s+", " ", re.sub(r"<.*?>", "", c)).replace("&middot;", "·").strip()
                        for c in cells]
    return None


def _f(x):
    """first number in a cell, thousands spaces removed (4-dp tolerant)."""
    m = re.search(r"-?\d[\d ,]*\.?\d*", str(x))
    return float(m.group(0).replace(" ", "").replace(",", "")) if m else None


def check_link_counts(verbose: bool) -> list[str]:
    """The published sources page must quote the counts that are in the evidence file.

    WHY.  On 2026-09-16 the verification workflow rewrote docs/link_verification.json on main while
    the already-built docs/sources.html kept the previous run's numbers (10 bot-blocks / 54 OK
    against 16 / 51 + 3 broken).  The page was therefore asserting a measurement that no longer
    existed - precisely the failure this project is built to avoid.  The workflow now rebuilds the
    site after measuring, and this check makes the disagreement impossible to ship even if it does
    not: every count rendered on the page must equal the count in the JSON it came from.
    """
    problems: list[str] = []
    lv_path = ROOT / "docs/link_verification.json"
    html_path = ROOT / "docs/sources.html"
    if not (lv_path.exists() and html_path.exists()):
        return problems
    data = json.loads(lv_path.read_text(encoding="utf-8"))
    wanted = dict(data.get("summary_counts", {}))
    html = html_path.read_text(encoding="utf-8")
    start = html.find("Live link verification")
    if start < 0:
        return ["docs/sources.html does not contain the live link verification section"]
    end = html.find("Expected non-200 responses", start)
    seg = html[start:end if end > start else start + 4000]
    shown = {k: int(n) for k, n in re.findall(r'class="pill [^"]*">([A-Z_0-9]+): (\d+)<', seg)}
    # the file must agree with itself: `problems` is exactly the set of rows whose class is
    # neither expected-ok nor expected-non-ok, and `n_problems` is its length
    cls = data.get("classification") or {}
    expected = tuple(cls.get("expected_ok", ["OK"])) + tuple(cls.get("expected_non_ok",
                                                                    ["BOT_BLOCKED",
                                                                     "LOGIN_REQUIRED",
                                                                     "AUTH_REQUIRED"]))
    rows = data.get("results", [])
    if rows:
        derived = [r["url"] for r in rows if not str(r.get("result", "")).startswith(expected)]
        listed = [p.get("url") for p in data.get("problems", [])]
        if sorted(derived) != sorted(listed):
            problems.append(f"docs/link_verification.json is internally inconsistent: "
                            f"n_problems={data.get('n_problems')} but {len(derived)} row(s) fall "
                            f"outside {list(expected)}")
        if data.get("n_problems") != len(listed):
            problems.append(f"docs/link_verification.json: n_problems={data.get('n_problems')} "
                            f"!= len(problems)={len(listed)}")
        if verbose and not problems:
            print(f"  ok   link evidence self-consistent ({len(rows)} rows, "
                  f"{len(derived)} needing review)")

    if shown != wanted:
        only_page = {k: v for k, v in shown.items() if wanted.get(k) != v}
        only_json = {k: v for k, v in wanted.items() if shown.get(k) != v}
        problems.append(f"docs/sources.html link counts disagree with docs/link_verification.json: "
                        f"page {only_page} vs evidence {only_json} "
                        f"(regenerate with `python scripts/build_site.py`)")
    elif verbose:
        print(f"  ok   sources.html counts == link_verification.json ({len(wanted)} classes)")
    return problems


def check_tables(verbose: bool) -> list[str]:
    problems: list[str] = []
    html = (ROOT / "docs/results.html").read_text(encoding="utf-8")
    var_json = ROOT / "outputs_recon/submission_variants.json"
    if var_json.exists():
        v = json.loads(var_json.read_text())
        by_name = {r["variant"]: r for r in v["variants"]}
        for label, key in SHAPING_ROWS.items():
            cells = _row_cells(html, label, min_cells=5)
            if cells is None:
                problems.append(f"shaping table: row for {label!r} not found in docs/results.html")
                continue
            if key not in by_name:
                problems.append(f"artifact has no variant {key!r}; docs cite it")
                continue
            want, got = round(by_name[key]["dti"], 4), _f(cells[1])
            if want != got:
                problems.append(f"shaping table {label!r}: docs DTI {got} != artifact {want}")
            mass, fp = _f(cells[3]), _f(cells[2])
            if mass is not None and abs(mass - by_name[key]["prob_mass"]) > 1.0:
                problems.append(f"shaping table {label!r}: docs mass {mass} != artifact {by_name[key]['prob_mass']}")
            if fp is not None and abs(fp - by_name[key]["FP_w"]) > 1.0:
                problems.append(f"shaping table {label!r}: docs FP_w {fp} != artifact {by_name[key]['FP_w']}")
            if verbose:
                print(f"  ok   shaping row {label[:38]!r} DTI={want}")
        best = v.get("threshold_search", {}).get("best") or {}
        bd = v.get("threshold_search", {}).get("dti")
        if best and bd is not None:
            hit = next((r for r in v["table"]
                        if r.get("thin") == best.get("thin") and abs(r["t0"] - best["t0"]) < 1e-6), None)
            cells = _row_cells(html, "grid-searched", min_cells=5)
            if hit and cells and round(hit["dti"], 4) != _f(cells[1]):
                problems.append(f"shaping table 'grid-searched': docs {_f(cells[1])} != artifact {round(hit['dti'], 4)}")
            if hit and cells and cells[3] != "&mdash;" and abs(_f(cells[3]) - hit["mass"]) > 1.0:
                problems.append(f"shaping table 'grid-searched' mass {_f(cells[3])} != artifact {hit['mass']}")
    else:
        print("  note outputs_recon/submission_variants.json absent (fresh machine) - "
              "shaping table not re-derived; run scripts/measure_submission_variants.py")

    summ = ROOT / "outputs_recon/inference_summary.json"
    if summ.exists():
        d = json.loads(summ.read_text())
        i = html.find('id="e2e"')
        j = html.find("</section>", i)
        sec = html[i:j] if i >= 0 else ""
        pre = f"{int(round(d['prob_mass_pre_shaping'])):,}".replace(",", " ")
        post = f"{int(round(d['prob_mass_post_shaping'])):,}".replace(",", " ")
        for what, needle in ((f"probability mass {pre} -> {post}", f"{pre} &rarr; {post}"),
                             (f"submission mean {d['mean']:.4f}", f"mean {d['mean']:.4f}"),
                             (f"grid {d['grid']['width']}x{d['grid']['height']}",
                              f"{d['grid']['width']}&times;{d['grid']['height']}")):
            if needle not in sec:
                problems.append(f"end-to-end table: docs do not state {what} as recorded by "
                                f"outputs_recon/inference_summary.json")
            elif verbose:
                print(f"  ok   e2e row: {what}")
    else:
        print("  note outputs_recon/inference_summary.json absent - end-to-end row not re-derived; "
              "run python -m src.inference (it now writes that file)")

    manifests = sorted((ROOT / "outputs_ab").glob("*/manifest.json")) if (ROOT / "outputs_ab").is_dir() else []
    if manifests:
        for arm in AB_ARMS:
            mp = ROOT / "outputs_ab" / arm / "manifest.json"
            if not mp.exists():
                problems.append(f"A/B table: {arm} arm has no manifest though outputs_ab/ exists")
                continue
            m = json.loads(mp.read_text())
            needle = "<code>" + arm + "</code>"
            sh = m.get("shaping") or {}
            cells = _row_cells(html, needle, min_cells=5) or _row_cells(html, arm, min_cells=5)
            if cells is None:
                problems.append(f"A/B table: no row for arm {arm!r} in docs/results.html")
                continue
            for col, key, what in ((1, "mean_heldout_dti", "shaped"), (2, "mean_heldout_dti_raw", "raw")):
                want, got = round(float(sh.get(key, -1)), 4), _f(cells[col]) if col < len(cells) else None
                if got is not None and want >= 0 and want != got:
                    problems.append(f"A/B table {arm} {what}: docs {got} != manifest {want}")
            want_t0 = round(float(sh.get("t0", 0)) * 1000) / 1000
            doc_t0 = re.search(r"t0=([\d.]+)", cells[3] if len(cells) > 3 else "")
            if doc_t0 and abs(float(doc_t0.group(1)) - float(sh.get("t0", 0))) > 2e-3:
                problems.append(f"A/B table {arm}: docs t0={doc_t0.group(1)} != manifest {sh.get('t0'):.3f}")
            per = [round(float(e["dti"]), 4) for e in m.get("models", [])]
            docs_per = [round(float(x), 4) for x in re.findall(r"0\.\d{4}", cells[4])] if len(cells) > 4 else []
            if per and docs_per and sorted(per) != sorted(docs_per):
                problems.append(f"A/B table {arm}: docs per-split {docs_per} != manifest {per}")
            if verbose:
                print(f"  ok   A/B {arm}: shaped={sh.get('mean_heldout_dti'):.4f} t0={want_t0}")
    else:
        print("  note outputs_ab/*/manifest.json absent - A/B table not re-derived; "
              "run scripts/run_ab_loss_experiment.sh")
    return problems



# ---- 5. links inside the published site must resolve there ---------------------------
# Pages publishes the `docs/` directory as the whole site, so a relative link that leaves docs/
# (../README.md) resolves outside the deployed tree and 404s.  Repo files that belong to the code
# rather than the site are therefore linked as absolute GitHub blob URLs - which this check then
# verifies really exist in the repo, so a repoint cannot quietly create a dangling link.
BLOB_PREFIX = "https://github.com/buffedlizard55-lab/GEMSDOE/blob/main/"


def check_published_links(verbose: bool) -> list[str]:
    problems: list[str] = []
    for f in sorted((ROOT / "docs").glob("*.html")):
        text = f.read_text(encoding="utf-8", errors="ignore")
        for href in set(re.findall(r'href="([^"#]+?)(?:#[^"]*)?"', text)):
            if href.startswith(("http://", "https://", "mailto:", "data:")):
                if href.startswith(BLOB_PREFIX):
                    rel = href[len(BLOB_PREFIX):]
                    if not (ROOT / rel).exists():
                        problems.append(f"{f.name}: blob link points at {rel}, which is not in the repo")
                    elif verbose:
                        print(f"  ok   {f.name} -> blob {rel}")
                continue
            if href.startswith("../") or href.startswith("/"):
                problems.append(f"{f.name}: href={href!r} leaves the published root (docs/ is the "
                                f"site) - link it as {BLOB_PREFIX}<path> instead")
                continue
            if href.endswith(".md"):
                problems.append(f"{f.name}: href={href!r} points at raw markdown inside the site; "
                                f"link the repo copy via GitHub or a docs/*.html page")
                continue
            if not (f.parent / href).exists():
                problems.append(f"{f.name}: href={href!r} is not in docs/ (would 404 on the site)")
            elif verbose:
                print(f"  ok   {f.name} -> {href}")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--verbose", action="store_true")
    a = ap.parse_args()
    all_problems = []
    for name, fn in (("file references", check_file_refs), ("data catalog", check_catalog),
                     ("published tables vs artifacts", check_tables),
                     ("published link counts vs evidence", check_link_counts),
                     ("published link targets", check_published_links),
                     ("url hygiene", check_urls)):
        print(f"== {name} ==")
        pr = fn(a.verbose)
        for x in pr:
            print("  FINDING:", x)
        all_problems += pr
    if all_problems:
        print(f"\nFAIL: {len(all_problems)} finding(s). Fix the doc or produce the artefact; "
              "do not delete the evidence trail.")
        return 1
    print(f"  ({len(WARNINGS)} uncatalogued-host link(s) listed above for human review; not "
          "failures - context links are allowed outside the data catalog)")
    print("\nPASS: no cited-but-missing artefacts, catalog internally consistent, published "
          "tables equal their artifacts, every site link resolves, and all documented hosts "
          "are in the audit table.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
