#!/usr/bin/env python3
"""Prove that the site's in-browser .tif generator really produces a submittable file.

WHY
---
docs/how_to_submit.html offers a button that writes a GeoTIFF in the reader's browser. That claim is
either measured or it is a hallucination, and a browser cannot be scored by CI. So this script runs
**the same JavaScript the page runs** (`docs/geotiff_writer.js`, through node) in a temporary
directory and then judges its output with tools that have no stake in the outcome:

  1. `scripts/build_submission_payload.py --check` - the shipped payload still reproduces the artifact
  2. node - the page's own code path; its self-checks must all pass
  3. rasterio - reads the generated file and compares its float32 buffer with the artifact's,
     bit for bit, plus CRS / resolution / transform / dtype / band count
  4. `scripts/validate_submission.py` - the repository's format gate, on the generated bytes
  5. zipfile - the .zip route's container is read back and the member compared with the .tif
  6. variants - uncompressed strips and one-row-per-strip, because a container that only works in
     the configuration it was written with is a container that will break on someone's browser

Writes data/evidence/site_generator.json; scripts/build_site.py renders it on the how-to-submit
page.  Exit 0 = every step passed, 1 = a real defect, 2 = a prerequisite is missing (no node, or
the payload has not been built) which is reported as MISSING rather than as a failure.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
import zipfile
from pathlib import Path

import numpy as np
import rasterio

ROOT = Path(__file__).resolve().parents[1]
WRITER = "docs/geotiff_writer.js"
META = "docs/submission_meta.json"
BLOB = "docs/submission_field.bin"
ARTIFACT = "data/evidence/runs/ens12-adopted-floor0.1-w0/submission.tif"
SAMPLE = "data/sample_submission.tif"
OUT_DEFAULT = "data/evidence/site_generator.json"


def run(cmd, cwd=ROOT, binary=False):
    p = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=not binary)
    return p


def sha256_file(p: Path) -> str:
    import hashlib
    h = hashlib.sha256()
    with p.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def node_version() -> str | None:
    exe = shutil.which("node")
    if not exe:
        return None
    p = run([exe, "--version"])
    return (p.stdout or "").strip() or None


def _profile(src) -> dict:
    return dict(width=src.width, height=src.height, count=src.count, dtype=src.dtypes[0],
                epsg=(src.crs.to_epsg() if src.crs else None),
                res=[float(src.res[0]), float(src.res[1])], nodata=str(src.nodata),
                transform=[float(x) for x in src.transform])


def compare_with_artifact(gen_path: Path, art_path: Path, sample_path: Path | None = None) -> dict:
    """Two separate judges, because two separate requirements are being tested.

    * the PIXELS must equal the artifact's, bit for bit - that is what "the same prediction" means;
    * the CONTAINER (grid, CRS, resolution, geotransform, dtype, NODATA) is judged against
      `sample_submission.tif`, the official format template, because the platform's sentence is
      "it must match the submission format's CRS, shape, and geotransform".  Judging the container
      against the artifact would have been wrong while the artifact carried no NODATA tag at all
      (true until the 2026-09-25 template conformance fix, see `container_note`); it is judged
      against the template either way, so a future container drift is caught the same manner.
    """
    with rasterio.open(gen_path) as g:
        ga, prof = g.read(1), _profile(g)
        prof["compression"] = str(g.compression)
        prof["tiled"] = bool(g.profile.get("tiled"))
        gb = np.ascontiguousarray(ga, dtype="<f4").tobytes()
    with rasterio.open(art_path) as a:
        aa = a.read(1)
        art_prof = _profile(a)
    ab = np.ascontiguousarray(aa, dtype="<f4").tobytes()
    same_grid = all(prof[k] == art_prof[k] for k in
                    ("width", "height", "count", "dtype", "epsg", "res", "transform"))
    n_diff = (-1 if not same_grid else
              int(np.count_nonzero(np.frombuffer(gb, dtype=np.uint32) !=
                                   np.frombuffer(ab, dtype=np.uint32))))
    out = dict(measured=prof, artifact=art_prof, grid_and_crs_match=same_grid,
               float32_bits_identical=(gb == ab), uint32_px_differing=n_diff,
               pixels=int(ga.size),
               one_px=int(np.count_nonzero(np.isfinite(ga) & (ga == 1.0))),
               nan_px=int(np.isnan(ga).sum()),
               container_note=(f"generated NODATA={prof['nodata']!r}, artifact NODATA="
                               f"{art_prof['nodata']!r}"
                               + (" (the artifact declares none)"
                                  if art_prof["nodata"] is None else
                                  " (matches the template since the 2026-09-25 conformance fix)")))
    if sample_path and Path(sample_path).exists():
        with rasterio.open(sample_path) as s:
            want = _profile(s)
        keys = ("width", "height", "count", "dtype", "epsg", "res", "transform", "nodata")
        mism = {k: [prof.get(k), want.get(k)] for k in keys if prof.get(k) != want.get(k)}
        out["container_vs_sample"] = dict(compared=list(keys), matches=not mism, mismatches=mism,
                                         sample=want)
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=OUT_DEFAULT)
    ap.add_argument("--keep", action="store_true", help="keep the temp dir and print its path")
    a = ap.parse_args(argv)

    t0 = time.time()
    report = dict(
        generated_utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        script="scripts/check_site_generator.py",
        purpose="the in-browser generator on docs/how_to_submit.html is executed here under node "
                "and its output is judged by rasterio and by the repository's own validator",
        artifact=ARTIFACT, writer=WRITER, format_template=SAMPLE,
        payload=dict(meta=META, field_blob=BLOB),
        steps=[],
    )

    def step(name, status, detail, source, note=""):
        report["steps"].append(dict(name=name, status=status, measured=detail, source=source,
                                    note=note))
        print(f"{status:<8} {name}: {note or ''}")
        return status

    out_path = ROOT / a.out if not Path(a.out).is_absolute() else Path(a.out)
    missing = [rel for rel in (WRITER, META, BLOB, ARTIFACT) if not (ROOT / rel).exists()]
    if missing:
        report["verdict"] = "MISSING"
        report["missing"] = missing
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(report, indent=1))
        print(f"MISSING prerequisites: {', '.join(missing)}")
        print("  build the payload with: python scripts/build_submission_payload.py")
        return 2

    exe = shutil.which("node")
    if not exe:
        report["verdict"] = "MISSING"
        report["reason"] = "node is not on PATH; the page's generator cannot be executed headlessly"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(report, indent=1))
        print("MISSING node - the browser-side writer cannot be verified headlessly here")
        return 2

    ok_all = True

    def hard(step_name, fn, source):
        """A crash in any step is a FAIL with the traceback in the evidence, not an abort: the
        evidence file has to exist even when the thing under test is broken."""
        nonlocal ok_all
        try:
            ok, detail = fn()
        except Exception as ex:
            import traceback
            ok, detail = False, dict(error=f"{type(ex).__name__}: {ex}",
                                      tail=traceback.format_exc().strip().splitlines()[-4:])
        ok_all &= bool(ok)
        return step(step_name, "PASS" if ok else "FAIL", detail, source,
                    "" if ok else str(detail)[:300])

    with tempfile.TemporaryDirectory(prefix="gems-gen-") as td:
        tmp = Path(td)

        # ---- 1. the payload still reproduces the artifact --------------------------------
        p = run([sys.executable, "scripts/build_submission_payload.py", "--check"])
        ok = p.returncode == 0
        ok_all &= ok
        step("payload matches the artifact", "PASS" if ok else "FAIL",
             dict(exit_code=p.returncode, stdout=(p.stdout or "").strip(),
                  stderr=(p.stderr or "").strip()[-400:]),
             "scripts/build_submission_payload.py --check",
             "" if ok else "the payload builder refused or reported drift")

        # ---- 2. the page's own code path, run by node -------------------------------------
        meta = json.loads((ROOT / META).read_text())
        tif, zip_ = tmp / "submission.tif", tmp / "submission.zip"
        p = run([exe, str(ROOT / WRITER), str(ROOT / META), str(ROOT / BLOB), str(tif), str(zip_)])
        node_ok = p.returncode == 0 and tif.exists()
        try:
            node_report = json.loads(p.stdout)
        except Exception:
            node_report = {"raw_stdout": (p.stdout or "")[-2000:],
                          "stderr": (p.stderr or "")[-2000:]}
        ok_all &= node_ok
        step("node ran the page's writer", "PASS" if node_ok else "FAIL",
             dict(exit_code=p.returncode, ok=node_report.get("ok"),
                  failed_checks=node_report.get("failed"),
                  self_checks=len(node_report.get("checks") or []),
                  bytes=node_report.get("bytes"), sha256=node_report.get("sha256"),
                  compression=node_report.get("compression"), layout=node_report.get("layout"),
                  node=node_version(),
                  reported_field_counts=node_report.get("field")),
             f"{WRITER} (the file the page loads)",
             "" if node_ok else (p.stderr or "")[-400:])

        # ---- 3. rasterio reads it and it equals the artifact bit for bit -------------------
        s3_detail = {}
        def _s3():
            cmp = compare_with_artifact(tif, ROOT / ARTIFACT, ROOT / SAMPLE)
            s3_detail.update(cmp)
            # compare_with_artifact omits container_vs_sample when the template is not placed
            # (fresh clone, data/ absent).  That is a MISSING MEASUREMENT, not a match: name it
            # loudly instead of crashing into a KeyError that hides the real gap.
            cv = cmp.get("container_vs_sample")
            ok = (cmp["grid_and_crs_match"] and cmp["float32_bits_identical"]
                  and cmp["uint32_px_differing"] == 0
                  and bool(cv is not None and cv["matches"]))
            step("rasterio profile of the generated file", "INFO", cmp["measured"], "rasterio",
                 f"generated {tif.stat().st_size:,} B vs artifact "
                 f"{(ROOT / ARTIFACT).stat().st_size:,} B (container differs; pixels do not)")
            if cv is None:
                return ok, dict(error=f"container vs template not judged: {SAMPLE} is not placed "
                                      "in this checkout (run scripts/assemble_data_bridge.py)", **cmp)
            return ok, cmp
        hard("rasterio reads it; pixels are the artifact's", _s3,
             "rasterio 1.x, independent of the writer")

        step("NODATA tag: artifact vs the official template", "INFO",
             dict(generated=s3_detail.get("measured", {}).get("nodata"),
                  artifact=s3_detail.get("artifact", {}).get("nodata"),
                  sample=(s3_detail.get("container_vs_sample") or {}).get("sample", {}).get("nodata")),
             "rasterio profiles",
             ("the generated file declares nan like the template; the committed artifact "
              "declares no NODATA tag - a container difference, not a pixel one"
              if s3_detail.get("artifact", {}).get("nodata") is None else
              "generated, artifact and template all declare nan since the 2026-09-25 "
              "template-conformance fix"))

        # ---- 4. the repository's own format gate ------------------------------------------
        def _s4():
            p = run([sys.executable, "scripts/validate_submission.py", "--pred", str(tif),
                     "--sample", "data/sample_submission.tif",
                     "--train", "data/training_features.tif"])
            text = (p.stdout or "") + (p.stderr or "")
            ok = p.returncode == 0 and "Validation PASSED" in text
            return ok, dict(exit_code=p.returncode,
                            lines=len([l for l in text.splitlines() if l.strip()]),
                            ticks=len([l for l in text.splitlines() if l.strip().startswith("✓")]),
                            tail=text.strip().splitlines()[-1] if text.strip() else "")
        hard("scripts/validate_submission.py on the generated bytes", _s4,
             "scripts/validate_submission.py")

        # ---- 5. the .zip route ---------------------------------------------------------------
        def _s5():
            with zipfile.ZipFile(zip_) as z:
                names = z.namelist()
                bad = z.testzip()
                member = z.read(names[0]) if names else b""
            same = member == tif.read_bytes()
            ok = names == ["submission.tif"] and bad is None and same
            return ok, dict(namelist=names, member_equals_tif=same,
                            zip_bytes=zip_.stat().st_size, tif_bytes=tif.stat().st_size)
        hard("the zipped route is a single-member zip of that file", _s5,
             "zipfile.testzip() + byte comparison")

        # ---- 6. container variants: the page must not depend on one configuration -----------
        variants = []
        for label, extra in (("uncompressed strips", ["--no-deflate"]),  # noqa: E501
                             ("one row per strip", ["--rows-per-strip", "1"]),
                             ("whole grid in one strip", ["--rows-per-strip", str(meta["grid"]["height"])])):
            def _v(vt=tmp / f"variant_{len(variants)}.tif", extra=extra, label=label):
                p = run([exe, str(ROOT / WRITER), str(ROOT / META), str(ROOT / BLOB), str(vt)] + extra)
                row = dict(name=label, args=extra, exit_code=p.returncode, path=str(vt))
                if p.returncode == 0 and vt.exists():
                    c = compare_with_artifact(vt, ROOT / ARTIFACT, ROOT / SAMPLE)
                    cv = c.get("container_vs_sample")
                    row.update(readable=True, bits_identical=c["float32_bits_identical"],
                               grid_ok=c["grid_and_crs_match"], bytes=vt.stat().st_size,
                               container_ok=bool(cv is not None and cv["matches"]),
                               self_reported_ok=bool(json.loads(p.stdout).get("ok")))
                    ok = (c["float32_bits_identical"] and c["grid_and_crs_match"]
                          and cv is not None and cv["matches"] and row["self_reported_ok"])
                    if cv is None:
                        row["error"] = (f"container vs template not judged: {SAMPLE} is not "
                                        "placed in this checkout (run scripts/assemble_data_bridge.py)")
                else:
                    ok, row["error"] = False, (p.stderr or "")[-300:]
                variants.append(row)
                return ok, row
            hard(f"variant: {label}", _v, "node + rasterio")

        if a.keep:
            print("kept:", tmp)
        else:
            for f in (tif, zip_):
                if f.exists():
                    pass  # tmp context manager removes them

    report["verdict"] = "PASS" if ok_all else "FAIL"
    report["summary"] = dict(
        steps=len(report["steps"]),
        passed=sum(1 for s in report["steps"] if s["status"] == "PASS"),
        failed=sum(1 for s in report["steps"] if s["status"] == "FAIL"),
        node=node_version(),
        payload_meta_sha256=sha256_file(ROOT / META),
        payload_blob_sha256=sha256_file(ROOT / BLOB),
        blob_bytes=(ROOT / BLOB).stat().st_size,
        encoding=meta.get("encoding"),
        artifact_sha256=sha256_file(ROOT / ARTIFACT),
        artifact_bytes=(ROOT / ARTIFACT).stat().st_size,
        variants=variants,
    )
    report["seconds"] = round(time.time() - t0, 2)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(report, indent=1))
    print(f"wrote {a.out}  verdict={report['verdict']}  "
          f"({report['summary']['passed']}/{report['summary']['steps']} steps, "
          f"{report['seconds']} s)")
    return 0 if ok_all else 1


if __name__ == "__main__":
    raise SystemExit(main())
